print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
print('Hello, World!')
print('gonna use python to do data analysis or test code in simulation or smth like that, basically any automated task that isn\'t uploaded to the microcontroller')
